import Link from 'next/link';

export default function TokensPage() {
  return (
    <main className="flex min-h-screen flex-col items-center p-4 sm:p-6 md:p-8 bg-white text-black">
      <div className="w-full max-w-4xl">
        <Link href="/" className="text-blue-600 hover:underline mb-6 inline-block text-sm">
          &larr; Back to Home
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold mb-6 text-black text-center">BitCDN Token Ecosystem & Economic Model</h1>

        <section className="bg-gray-100 p-4 sm:p-5 rounded-lg shadow-xl mb-6">
          <h2 className="text-xl sm:text-2xl font-semibold mb-3 text-black">Core Principles & Token Roles</h2>
          <p className="text-sm text-gray-700 leading-relaxed mb-4">
            The BitCDN economic model is designed with distinct layers to ensure fair compensation for network participants and clear revenue streams for content creators and rights holders. It separates the payment for infrastructure services from the revenue generated by the content itself.
          </p>
          <p className="text-sm text-gray-700 leading-relaxed mb-2">
            1. <strong>Infrastructure & Service Payments:</strong> Participants who provide storage and bandwidth (seeders) are compensated directly for their contributions. This is primarily handled via efficient micropayments (e.g., using BSV or other stablecoins), ensuring that the operational costs of the network are covered transparently.
          </p>
          <p className="text-sm text-gray-700 leading-relaxed mb-4">
            2. <strong>Content Revenue & Ownership:</strong> Content creators, artists, and their investors retain primary ownership and revenue rights to their work. BitCDN facilitates the distribution and monetization of this content, with mechanisms to ensure that revenue flows back to the rightful owners according to pre-defined shares. The BitCDN platform itself may take a small service fee from these content transactions.
          </p>
          
          <p className="text-sm text-gray-700 leading-relaxed mb-4">
            Explore the specific tokens and mechanisms involved:
          </p>
          <ul className="list-disc list-inside text-sm text-gray-700 space-y-2 leading-relaxed">
            <li>
              <Link href="/bitcdn-token" className="text-blue-600 hover:underline">
                <strong>The $BITCDN Token:</strong> Learn about the potential roles of a native platform token, which could include governance of the BitCDN platform, staking for network participation, or distributing platform service fees.
              </Link>
            </li>
            <li>
              <Link href="/content-tokens" className="text-blue-600 hover:underline">
                <strong>Content Tokens:</strong> Discover how unique tokens can represent ownership shares or access rights to specific pieces of content, enabling transparent revenue distribution from content sales or consumption to artists, investors, and other stakeholders.
              </Link>
            </li>
          </ul>
        </section>
      </div>
    </main>
  );
} 