import Link from 'next/link';

export default function TokensPage() {
  return (
    <main className="flex min-h-screen flex-col items-center p-4 sm:p-6 md:p-8 bg-white text-black">
      <div className="w-full max-w-4xl">
        <Link href="/" className="text-blue-600 hover:underline mb-6 inline-block text-sm">
          &larr; Back to Home
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold mb-6 text-black text-center">BitCDN Token Ecosystem & Economic Model</h1>

        <section className="bg-gray-100 p-4 sm:p-5 rounded-lg shadow-xl mb-6">
          <h2 className="text-xl sm:text-2xl font-semibold mb-3 text-black">Core Economic Layers & Token Functions</h2>
          <p className="text-sm text-gray-700 leading-relaxed mb-2">
            The BitCDN economic model is built on two distinct layers to ensure fair compensation for network infrastructure providers and to empower content creators and platforms with flexible monetization tools for their digital assets. This separation is key to a sustainable and equitable ecosystem.
          </p>
          
          <div className="mb-4 p-3 bg-white rounded-md shadow">
            <h3 className="text-lg font-semibold text-gray-800 mb-1">Layer 1: Infrastructure Compensation</h3>
            <p className="text-xs text-gray-600 leading-relaxed">
              Node operators (seeders) who provide the essential bandwidth and storage for the P2P network are compensated directly for their services. This is achieved through real-time micropayments (e.g., using BSV or other efficient stablecoins) made by the content consumer or the platform delivering the content. This compensation is for the utility of data delivery and is independent of the specific content's revenue model or ownership.
            </p>
          </div>

          <div className="mb-4 p-3 bg-white rounded-md shadow">
            <h3 className="text-lg font-semibold text-gray-800 mb-1">Layer 2: Content Monetization & Ownership</h3>
            <p className="text-xs text-gray-600 leading-relaxed">
              This layer addresses the intellectual property value. Content creators and rights holders can tokenize their content, enabling transparent revenue sharing and new forms of digital ownership. BitCDN aims to provide tools and standards for:
            </p>
            <ul className="list-disc list-inside text-xs text-gray-600 space-y-1 mt-2 pl-4">
              <li><strong>Fungible Tokens (FTs) for Revenue Shares:</strong> Representing a proportional stake in the revenue generated by a specific piece of content (e.g., $SONG1). When users pay for this content, revenue is distributed to FT holders.</li>
              <li><strong>Non-Fungible Tokens (NFTs) for Access & Collectibles:</strong> Representing unique rights, such as a lifetime access pass, a timed viewing ticket, or a special edition digital collectible.</li>
            </ul>
            <p className="text-xs text-gray-600 leading-relaxed mt-2">
              Content platforms integrating BitCDN can leverage these token types to build diverse monetization strategies.
            </p>
          </div>
          
          <p className="text-sm text-gray-700 leading-relaxed mb-3 mt-5">
            Explore the specific token types and their potential roles within this ecosystem:
          </p>
          <ul className="list-disc list-inside text-sm text-gray-700 space-y-2 leading-relaxed">
            <li>
              <Link href="/bitcdn-token" className="text-blue-600 hover:underline">
                <strong>The $BITCDN Platform Token:</strong> Explore the native token of the BitCDN platform. Learn how it's used for capital formation, distributing platform service fees to stakers, governance, and incentivizing network participation.
              </Link>
            </li>
            <li>
              <Link href="/content-tokens" className="text-blue-600 hover:underline">
                <strong>Content Tokens (FTs & NFTs):</strong> Delve deeper into how Fungible Tokens can manage revenue shares for specific content and how Non-Fungible Tokens can represent unique access rights or digital collectibles within the BitCDN framework.
              </Link>
            </li>
          </ul>
        </section>
      </div>
    </main>
  );
} 