import Link from 'next/link';

export default function ContentTokensPage() {
  return (
    <main className="flex min-h-screen flex-col items-center p-4 sm:p-6 md:p-8 bg-white text-black">
      <div className="w-full max-w-4xl">
        <Link href="/tokens" className="text-blue-600 hover:underline mb-6 inline-block text-sm">
          &larr; Back to Token Ecosystem Overview
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold mb-6 text-black text-center">Content Tokens: FTs & NFTs</h1>

        <section className="bg-gray-100 p-4 sm:p-5 rounded-lg shadow-xl mb-6">
          <h2 className="text-xl sm:text-2xl font-semibold mb-3 text-black">Monetizing & Managing Digital Content Rights</h2>
          <p className="text-sm text-gray-700 leading-relaxed mb-2">
            Content Tokens are central to BitCDN's Layer 2 economic model, focusing on the monetization of intellectual property and the management of access rights. They enable creators, rights holders, and platforms to define how revenue is shared and how content is accessed, all recorded transparently on-chain. These tokens are distinct from the direct micropayments (e.g., BSV, stablecoins) made to seeders for infrastructure services.
          </p>
          
          <div className="mb-4 p-3 bg-white rounded-md shadow">
            <h3 className="text-lg font-semibold text-gray-800 mb-1">Fungible Tokens (FTs) for Revenue Sharing</h3>
            <p className="text-xs text-gray-600 leading-relaxed mb-2">
              Fungible Tokens can be issued for specific pieces of content (e.g., a song titled "$SONG1", an ebook "$BOOKX") to represent proportional shares of the revenue generated by that content. 
            </p>
            <ul className="list-disc list-inside text-xs text-gray-600 space-y-1 pl-4 mb-2">
              <li><strong>Example:</strong> An artist releases a new single and issues 1,000,000 $SINGLE_XYZ FTs. They might keep 50% for themselves, allocate 30% to investors who funded the production, and offer 20% for public sale or to early supporters.</li>
              <li><strong>Mechanism:</strong> When a consumer pays to stream or download the single via a BitCDN-integrated platform, the net revenue (after any platform service fees) is programmatically distributed to all holders of $SINGLE_XYZ tokens according to their percentage ownership.</li>
              <li><strong>Tradability:</strong> These FTs can be traded on decentralized exchanges (DEXs), allowing for price discovery and liquidity for content revenue streams.</li>
            </ul>
            <p className="text-xs text-gray-600 leading-relaxed">
              This model offers a transparent and automated way to manage complex revenue splits for collaborative works or investor-funded projects.
            </p>
          </div>

          <div className="mb-4 p-3 bg-white rounded-md shadow">
            <h3 className="text-lg font-semibold text-gray-800 mb-1">Non-Fungible Tokens (NFTs) for Access & Collectibles</h3>
            <p className="text-xs text-gray-600 leading-relaxed mb-2">
              Non-Fungible Tokens are ideal for representing unique rights or items related to content.
            </p>
            <ul className="list-disc list-inside text-xs text-gray-600 space-y-1 pl-4 mb-2">
              <li><strong>Access Passes/Tickets:</strong> An NFT could grant lifetime access to a premium content library, a one-time viewing ticket for a live-streamed event, or season access to a series.</li>
              <li><strong>Digital Collectibles:</strong> Limited edition digital artwork, behind-the-scenes footage, or uniquely signed copies of content can be issued as NFTs, creating new value for fans and collectors.</li>
              <li><strong>Verifiable Ownership:</strong> NFTs provide provable ownership of these unique digital assets or rights, recorded on the blockchain.</li>
            </ul>
            <p className="text-xs text-gray-600 leading-relaxed">
              These NFTs can also be tradable, creating secondary markets for these unique access rights or collectibles.
            </p>
          </div>

          <p className="text-sm text-gray-700 leading-relaxed mt-4">
            BitCDN aims to provide SDKs and smart contract templates to make it easier for content platforms and creators to issue and manage both FTs for revenue sharing and NFTs for access/collectibles, fostering a vibrant and flexible digital content economy.
          </p>
        </section>
      </div>
    </main>
  );
} 