import Link from 'next/link';

export default function ContentTokensPage() {
  return (
    <main className="flex min-h-screen flex-col items-center p-4 sm:p-6 md:p-8 bg-white text-black">
      <div className="w-full max-w-4xl">
        <Link href="/tokens" className="text-blue-600 hover:underline mb-6 inline-block text-sm">
          &larr; Back to Token Ecosystem Overview
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold mb-6 text-black text-center">Content Tokens: Master NFTs, Revenue FTs, & Access NFTs</h1>

        <section className="bg-gray-100 p-4 sm:p-5 rounded-lg shadow-xl mb-6">
          <h2 className="text-xl sm:text-2xl font-semibold mb-3 text-black">Tokenizing Content: A Multi-Layered Approach</h2>
          <p className="text-sm text-gray-700 leading-relaxed mb-4">
            Content Tokens are central to BitCDN's Layer 2 economic model, focusing on the monetization of intellectual property and the management of access rights. This involves different types of tokens working together to represent the content itself, its revenue shares, and unique access privileges. These are distinct from direct micropayments to seeders (Layer 1) and the $BITCDN platform token.
          </p>
          
          <div className="mb-6 p-3 bg-white rounded-md shadow">
            <h3 className="text-lg font-semibold text-blue-700 mb-2">1. The Master Content NFT: Representing the Core IP</h3>
            <p className="text-xs text-gray-700 leading-relaxed mb-2">
              A single, unique Non-Fungible Token (NFT) can be created to represent a specific piece of content in its entirety – for example, an artist's master recording of a song, a film, or a published book. This 'Master Content NFT' serves as the definitive on-chain identifier for the intellectual property.
            </p>
            <ul className="list-disc list-inside text-xs text-gray-600 space-y-1 pl-4 mb-2">
              <li><strong>Uniqueness:</strong> Only one Master Content NFT exists for each unique creative work.</li>
              <li><strong>Revenue Aggregation Point:</strong> The address associated with this NFT can act as the initial collection point for revenues generated by the consumption of the content (after platform fees and seeder payments).</li>
              <li><strong>Tradability of Master Rights:</strong> The Master Content NFT itself could potentially be sold or transferred, representing a sale of the underlying master rights to the content.</li>
            </ul>
          </div>

          <div className="mb-6 p-3 bg-white rounded-md shadow">
            <h3 className="text-lg font-semibold text-blue-700 mb-2">2. Revenue Share Fungible Tokens (FTs): Distributing Earnings</h3>
            <p className="text-xs text-gray-700 leading-relaxed mb-2">
              Associated with a Master Content NFT, a series of Fungible Tokens (FTs) can be issued to represent proportional shares of the revenue collected by that Master Content NFT.
            </p>
            <ul className="list-disc list-inside text-xs text-gray-600 space-y-1 pl-4 mb-2">
              <li><strong>Example:</strong> An artist releases a new single, represented by a Master Content NFT. They then issue 1,000,000 'ArtistX_SingleShare' FTs. These FTs are distributed among the artist, investors, collaborators, etc.</li>
              <li><strong>Mechanism:</strong> Revenue collected at the Master Content NFT's address is programmatically distributed to all holders of the associated 'ArtistX_SingleShare' FTs according to their percentage ownership.</li>
              <li><strong>Liquidity & Price Discovery:</strong> These Revenue Share FTs can be traded on decentralized exchanges (DEXs), allowing for liquid markets and price discovery for stakes in content revenue streams.</li>
            </ul>
            <p className="text-xs text-gray-600 leading-relaxed">
              This two-tier system (Master NFT + Revenue Share FTs) offers a clear and transparent way to manage and distribute earnings from creative works to multiple stakeholders.
            </p>
          </div>

          <div className="mb-4 p-3 bg-white rounded-md shadow">
            <h3 className="text-lg font-semibold text-blue-700 mb-2">3. Access & Collectible NFTs: Unique Rights & Editions</h3>
            <p className="text-xs text-gray-700 leading-relaxed mb-2">
              Separately from the Master Content NFT and its Revenue Share FTs, other NFTs can be used for specific access privileges or as digital collectibles related to the content.
            </p>
            <ul className="list-disc list-inside text-xs text-gray-600 space-y-1 pl-4 mb-2">
              <li><strong>Access Passes/Tickets:</strong> An NFT could grant lifetime access to a premium content library, a one-time viewing ticket for a live-streamed event, or season access to a series. These don't necessarily grant revenue share but provide utility.</li>
              <li><strong>Digital Collectibles:</strong> Limited edition digital artwork, behind-the-scenes footage, or uniquely signed copies of content can be issued as NFTs.</li>
              <li><strong>Verifiable Ownership:</strong> These NFTs provide provable ownership of unique digital assets or rights.</li>
            </ul>
            <p className="text-xs text-gray-600 leading-relaxed">
              These types of NFTs can also be tradable, creating secondary markets for unique access or collectible items.
            </p>
          </div>

          <p className="text-sm text-gray-700 leading-relaxed mt-5">
            BitCDN aims to provide SDKs and smart contract templates to facilitate the creation and management of this comprehensive suite of content-related tokens, enabling a rich and flexible digital content economy.
          </p>
        </section>
      </div>
    </main>
  );
} 